version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: lastdatabase